export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";
export const MOVE_INGREDIENT = "MOVE_INGREDIENT";
export const INITIAL_STATE_BURGER_CONSTRUCTOR_TARGET =
  "INITIAL_STATE_BURGER_CONSTRUCTOR_TARGET";

export const getInitialStateForBurgerConstructorTarget = () => {
  return {
    type: INITIAL_STATE_BURGER_CONSTRUCTOR_TARGET,
  };
};
